ethereum:
  name: "Ethereum Mainnet"
  chain_id: 1
  rpc_url: "https://ethereum-rpc.publicnode.com"
  scan_api_url: "https://api.etherscan.io/v2/api"
  explorer_url: "https://etherscan.io"
  etherscan_api_key: "4TNC63YESA1EHV7N1EGFQX6K51KETRHN6I"

tron:
  name: "Tron Mainnet"
  chain_id: 728126428
  rpc_url: "https://api.trongrid.io"
  scan_api_url: "https://api.trongrid.io/v1"
  explorer_url: "https://tronscan.org"
  usdt_contract: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
  trongrid_api_key: "e53160ed-54c9-47c4-8d34-c80eb0433c70"

polygon:
  name: "Polygon PoS"
  chain_id: 137
  rpc_url: "https://polygon-rpc.com"
  scan_api_url: "https://api.etherscan.io/v2/api"
  explorer_url: "https://polygonscan.com"
  etherscan_api_key: "4TNC63YESA1EHV7N1EGFQX6K51KETRHN6I"

arbitrum:
  name: "Arbitrum One"
  chain_id: 42161
  rpc_url: "https://arb1.arbitrum.io/rpc"
  scan_api_url: "https://api.etherscan.io/v2/api"
  explorer_url: "https://arbiscan.io"
  etherscan_api_key: "4TNC63YESA1EHV7N1EGFQX6K51KETRHN6I"


